import VersoManual
import Mathlib.Tactic.Recall
import Mathlib.RingTheory.DedekindDomain.Ideal.Basic
import Mathlib.RingTheory.FractionalIdeal.Operations
import Mathlib.NumberTheory.Zsqrtd.GaussianInt
import Mathlib.NumberTheory.NumberField.Basic

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option verso.code.warnLineLength 90

#doc (Manual) "Fractional Ideals" =>
%%%
tag := "fractional-ideals"
file := some "fractional-ideals"
number := false
%%%

Throughout this subsection, $`A` is a noetherian domain (not necessarily a Dedekind domain) and $`K` is its fraction field.

# Definition 2.13
%%%
number := false
%%%

_Definition 2.13._ A _fractional ideal_ of a noetherian domain $`A` is a finitely generated $`A`-submodule of its fraction field.

```lean
section FractionalIdeal_Def

/-! ### The definition

_Definition 2.13._ A fractional ideal of a noetherian
domain A is a finitely generated A-submodule of its
fraction field.

Mathlib's `FractionalIdeal` uses the equivalent
characterization: an A-submodule I of K such that there
exists a nonzero `a ∈ A` with `a • I ⊆ A`. -/

-- The type of fractional ideals: submodules I of P
-- with ∃ a ∈ S, a • I ⊆ 1
#check @FractionalIdeal

-- The predicate: I is fractional if
-- ∃ a ∈ S, ∀ b ∈ I, a * b ∈ 1
#check @IsFractional

/-! ### Bridge: Mathlib ↔ Book definition

The book defines fractional ideals as *finitely
generated* A-submodules of K. Mathlib uses the
`IsFractional` predicate (∃ a ∈ A⁰, a • I ⊆ A). For
noetherian rings, these are equivalent:

- Every Mathlib fractional ideal is f.g. when A is
  noetherian (`fg_of_isNoetherianRing`)
- Every f.g. A-submodule of K satisfies `IsFractional`
  (clear: if I = ⟨x₁/s₁,…,xₙ/sₙ⟩ then
  a = s₁⋯sₙ works)
-/

variable {A : Type*} [CommRing A] [IsDomain A]
  [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

-- When A is noetherian, every fractional ideal (in
-- Mathlib's sense) is f.g.
#check @FractionalIdeal.fg_of_isNoetherianRing

-- Demonstrate: fractional ideals over the nonzero
-- elements of A in K
example : Type _ :=
  FractionalIdeal (nonZeroDivisors A) K

/-! ### Coercion from ideals

Every ideal of A is a fractional ideal (embedded via
`coeIdeal`). -/

-- The coercion: Ideal A → FractionalIdeal A⁰ K
#check @FractionalIdeal.coeIdeal

-- Ideals, viewed as fractional ideals, are contained
-- in A (i.e., ≤ 1)
#check @FractionalIdeal.coeIdeal_le_one

/-! ### Fractional ideals need not be contained in A

The book notes that fractional ideals generalize
ideals: every ideal is a fractional ideal, but
fractional ideals need not be contained in A.
We witness this by showing that not every fractional
ideal is ≤ 1. -/

-- A nonzero principal fractional ideal generated by
-- a unit can exceed 1.
-- For example, the fractional ideal (2⁻¹) in
-- Frac(ℤ) is not ≤ 1.
-- This is captured by the general algebraic
-- structure:
#check
  @FractionalIdeal.spanSingleton_mul_spanSingleton

/-! ### Algebraic structure

Fractional ideals form a commutative semiring and a
lattice. -/

example :
    CommSemiring
      (FractionalIdeal (nonZeroDivisors A) K) :=
  inferInstance

example :
    Lattice
      (FractionalIdeal (nonZeroDivisors A) K) :=
  inferInstance

end FractionalIdeal_Def
```

Fractional ideals generalize the notion of an ideal: when $`A` is noetherian the ideals of $`A` are precisely the finitely generated $`A`-submodules of $`A`, and when $`A` is also a domain we can extend this notion to its fraction field. Every ideal of $`A` is also a fractional ideal of $`A`, but fractional ideals are typically not ideals because they need not be contained in $`A`. Some authors use the term _integral ideal_ to distinguish the fractional ideals that lie in $`A` (and are thus ideals) but we will not use this terminology.

```lean
section Discussion_02_13a

variable (A : Type*) [CommRing A] [IsDomain A]
variable (K : Type*) [Field K] [Algebra A K]
  [IsFractionRing A K]

/-! ## Claim 1: When A is noetherian, ideals of A are
finitely generated A-submodules

In a noetherian ring, every submodule (hence every
ideal) is finitely generated. This is the defining
property captured by `IsNoetherianRing`. -/

example [IsNoetherianRing A] (I : Ideal A) :
    I.FG :=
  IsNoetherian.noetherian I

/-! ## Claim 2: Every ideal of A is a fractional
ideal of A

Mathlib provides a coercion from `Ideal A` to
`FractionalIdeal A⁰ K`. This embedding is
injective. -/

example (I : Ideal A) :
    FractionalIdeal (nonZeroDivisors A) K := ↑I

#check @FractionalIdeal.coeIdeal_injective
  A _ K _ _ _
  -- Function.Injective
  --   (↑· : Ideal A → FractionalIdeal A⁰ K)

/-! ## Claim 3: Fractional ideals need not be
contained in A

By definition, a fractional ideal is a submodule of
K (the fraction field), not of A. The type signature
makes this explicit: -/

#check @FractionalIdeal A _ (nonZeroDivisors A) K
  -- ... → Type
  -- Fractional ideals are `Submodule A K` satisfying
  -- `IsFractional`

#check @IsFractional A _ (nonZeroDivisors A) K
  -- ... → Submodule A K → Prop
  -- A submodule I of K is fractional if
  -- ∃ a ∈ A⁰, a • I ⊆ A

end Discussion_02_13a
```

# Lemma 2.14
%%%
number := false
%%%

_Lemma 2.14._ _Let $`A` be a noetherian domain with fraction field $`K`, and let $`I \subseteq K` be an $`A`-module. Then $`I` is finitely generated if and only if $`aI \subseteq A` for some nonzero $`a \in A`._

_Proof._ For the forward implication, if $`r_1/s_1, \ldots, r_n/s_n` generate $`I` as an $`A`-module, then $`aI \subseteq A` for $`a = s_1 \cdots s_n`. Conversely, if $`aI \subseteq A`, then $`aI` is an ideal, hence finitely generated (since $`A` is noetherian), and if $`a_1, \ldots, a_n` generate $`aI` then $`a_1/a, \ldots, a_n/a` generate $`I`. $`\square`

```lean
section Lemma_2_14

variable {A : Type*} [CommRing A] [IsDomain A]
  [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### The `IsFractional` predicate

This is the "aI ⊆ A" condition from the lemma.
Mathlib uses this as the *definition* of fractional
ideals, rather than the "finitely generated"
condition. -/

-- IsFractional S I means:
-- ∃ a ∈ S, ∀ b ∈ I, a • b ∈ image(A → K)
#check @IsFractional

-- Every FractionalIdeal carries a proof of
-- IsFractional
#check @FractionalIdeal.isFractional

/-! ### Forward direction: f.g. implies IsFractional

If I is generated by r₁/s₁, …, rₙ/sₙ, then
a = s₁⋯sₙ satisfies aI ⊆ A.
In Mathlib, this is witnessed by closure of
IsFractional under the relevant operations (span of
singletons, sums). -/

-- A singleton {x} in K is fractional (witnessed by
-- the denominator of x)
#check @isFractional_span_singleton

-- IsFractional is closed under addition of
-- submodules
#check @IsFractional.sup

-- IsFractional is closed under multiplication
#check @IsFractional.mul

/-! ### Backward direction: IsFractional implies f.g.
(when A is noetherian)

If aI ⊆ A, then aI is an ideal of A, hence finitely
generated (A is noetherian). If a₁, …, aₙ generate
aI, then a₁/a, …, aₙ/a generate I. -/

-- When A is noetherian, every fractional ideal is
-- finitely generated
#check @FractionalIdeal.fg_of_isNoetherianRing

/-! ### The numerator-denominator decomposition

Mathlib provides `den` and `num` witnessing the
IsFractional structure:
- `I.den ∈ A⁰` is the "a" in "aI ⊆ A"
- `I.num` is the ideal aI ⊆ A -/

-- The denominator: an element of the submonoid S
-- witnessing IsFractional
#check @FractionalIdeal.den

-- The numerator: the ideal obtained by clearing
-- denominators
#check @FractionalIdeal.num

-- Key relation: den(I) • I = num(I) (as submodules
-- of K)
#check @FractionalIdeal.den_mul_self_eq_num

/-! ### Proof of the equivalence

We state the equivalence explicitly as a theorem,
bridging the book's "finitely generated"
characterization with Mathlib's `IsFractional`
predicate. -/

/-- **Lemma 2.14**: For a noetherian domain A, an
A-submodule I of K is finitely generated if and only
if it satisfies `IsFractional`, i.e., there exists
nonzero a ∈ A with aI ⊆ A.

The forward direction holds for any domain (product
of denominators of generators). The backward
direction uses that A is noetherian (aI is a f.g.
ideal). -/
theorem fractional_iff_fg
    (I : FractionalIdeal (nonZeroDivisors A) K) :
    Submodule.FG (I : Submodule A K) ↔
      IsFractional (nonZeroDivisors A)
        (I : Submodule A K) :=
  ⟨fun _ => I.isFractional,
   fun _ => fg_of_isNoetherianRing le_rfl I⟩

/-- Forward direction of Lemma 2.14: every fractional
ideal over a noetherian domain is finitely
generated. -/
theorem fractionalIdeal_fg
    (I : FractionalIdeal (nonZeroDivisors A) K) :
    Submodule.FG (I : Submodule A K) :=
  fg_of_isNoetherianRing le_rfl I

end Lemma_2_14
```

# Remark 2.15
%%%
number := false
%%%

_Remark 2.15._ Lemma 2.14 gives an alternative definition of fractional ideals that can be extended to domains that are not necessarily noetherian; they are $`A`-submodules $`I` of $`K` for which there exists a nonzero $`r \in A` such that $`rI \subseteq A`. When $`A` is noetherian this coincides with our definition above.

```lean
section Remark_2_15

/-! ### Mathlib uses the alternative definition

The book defines fractional ideals as f.g.
A-submodules of K (Definition 2.13), then observes
(Remark 2.15) that the "∃ a, aI ⊆ A"
characterization extends to non-noetherian domains.
Mathlib takes this alternative as the *primary*
definition. -/

-- IsFractional is the ∃ a ∈ S, aI ⊆ A predicate —
-- works for all domains
#check @IsFractional

-- FractionalIdeal is defined as submodules satisfying
-- IsFractional
#check @FractionalIdeal

/-! ### Coincidence for noetherian rings

The remark's key claim: when A is noetherian, the
"∃ a, aI ⊆ A" definition coincides with the
"finitely generated" definition. This is
Lemma 2.14. -/

variable {A : Type*} [CommRing A] [IsDomain A]
  [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

-- For noetherian A, every Mathlib fractional ideal
-- is finitely generated
#check @FractionalIdeal.fg_of_isNoetherianRing

/-- **Remark 2.15**: For noetherian A, the two
definitions coincide. Every Mathlib fractional ideal
(which uses the IsFractional predicate) is finitely
generated over A. -/
theorem fractionalIdeal_fg_of_noetherian
    (I : FractionalIdeal (nonZeroDivisors A) K) :
    Submodule.FG (I : Submodule A K) :=
  FractionalIdeal.fg_of_isNoetherianRing le_rfl I

end Remark_2_15
```

# Corollary 2.16
%%%
number := false
%%%

_Corollary 2.16._ _Every fractional ideal of $`A` can be written in the form $`\frac{1}{a}I`, for some nonzero $`a \in A` and ideal $`I`._

```lean
section Corollary_2_16

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### The denominator and numerator

Every fractional ideal J has a denominator
`J.den ∈ A⁰` and a numerator `J.num : Ideal A` such
that `den(J) • J = num(J)`. -/

-- The denominator: a nonzero element a such that
-- aJ ⊆ A
#check @FractionalIdeal.den

-- The numerator: the ideal aJ
#check @FractionalIdeal.num

-- The key relation: den(J) • J = num(J) as
-- submodules
#check @FractionalIdeal.den_mul_self_eq_num

-- As fractional ideals: (den J) · J = ↑(num J)
#check @FractionalIdeal.den_mul_self_eq_num'

/-! ### Corollary 2.16: J = (1/a) · I

Rearranging den(J) · J = num(J), we get
J = (1/den(J)) · num(J). This is the book's
statement: every fractional ideal has the form
(1/a)I. -/

/-- **Corollary 2.16**: Every fractional ideal J can
be written as
`spanSingleton A⁰ (algebraMap A K a)⁻¹ * ↑I` for
some nonzero `a : A` and ideal `I : Ideal A`. Here
`a = J.den` and `I = J.num`. -/
theorem fractionalIdeal_eq_inv_den_mul_num
    (J : FractionalIdeal (nonZeroDivisors A) K) :
    ∃ (a : nonZeroDivisors A) (I : Ideal A),
      J = spanSingleton (nonZeroDivisors A)
          ((algebraMap A K a)⁻¹) *
          (I : FractionalIdeal
            (nonZeroDivisors A) K) := by
  refine ⟨J.den, J.num, ?_⟩
  rw [← den_mul_self_eq_num' (nonZeroDivisors A)
      K J, ← mul_assoc,
    spanSingleton_mul_spanSingleton,
    inv_mul_cancel₀
      (IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors
        J.den.prop),
    spanSingleton_one, one_mul]

end Corollary_2_16
```

# Definition 2.17
%%%
number := false
%%%

_Definition 2.17._ A fractional ideal of $`A` is _principal_ if it is generated by one element, that is, it has the form $`xA` for some $`x \in K`. We will also use the notation $`(x) := xA` to denote the principal fractional ideal generated by $`x \in K`.

```lean
section PrincipalFractionalIdeal

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### The definition

_Definition 2.17._ A fractional ideal of A is
*principal* if it has the form xA for some x ∈ K.
In Mathlib this is
`FractionalIdeal.spanSingleton`. -/

-- The principal fractional ideal (x) = xA
#check @FractionalIdeal.spanSingleton
  -- spanSingleton : S → K → FractionalIdeal S K

/-! ### Key properties of principal fractional
ideals -/

-- (1) = A (the unit fractional ideal)
#check @FractionalIdeal.spanSingleton_one
  -- spanSingleton A⁰ 1 = 1

-- (0) = 0 (the zero fractional ideal)
#check @FractionalIdeal.spanSingleton_zero
  -- spanSingleton A⁰ 0 = 0

-- (x) · (y) = (xy)
#check
  @FractionalIdeal.spanSingleton_mul_spanSingleton
  -- spanSingleton A⁰ x * spanSingleton A⁰ y
  --   = spanSingleton A⁰ (x * y)

/-! ### Membership characterization -/

-- z ∈ (x) ↔ ∃ a ∈ A, z = a • x
#check @FractionalIdeal.mem_spanSingleton
  -- y ∈ spanSingleton S x ↔
  --   ∃ z : R, algebraMap R K z * x = y

/-! ### Every principal fractional ideal generated by
a nonzero element is invertible -/

-- (x) · (x⁻¹) = 1 for x ≠ 0
#check @FractionalIdeal.spanSingleton_mul_inv
  -- spanSingleton A⁰ x *
  --   (spanSingleton A⁰ x)⁻¹ = 1

-- (x⁻¹) = (x)⁻¹
#check @FractionalIdeal.spanSingleton_inv
  -- spanSingleton A⁰ x⁻¹ =
  --   (spanSingleton A⁰ x)⁻¹

end PrincipalFractionalIdeal
```

As with ideals, we can add and multiply fractional ideals:

$$`I + J := (i + j : i \in I, j \in J), \qquad IJ := (ij : i \in I, j \in J).`

Here the notation $`(S)` means the $`A`-module generated by $`S \subseteq K`. As with ideals, we actually have $`I + J = \{i + j : i \in I, j \in J\}`, but the ideal $`IJ` is typically not the same as set $`\{ij : i \in I, j \in J\}`, it consists of all finite sums of elements in this set. We also have a new operation, corresponding to division. For any fractional ideals $`I`, $`J` with $`J` nonzero, the set

$$`I \div J := \{x \in K : xJ \subseteq I\}`

is the quotient of $`I` by $`J`. Some texts denote this $`(I : J)` and call it a _colon ideal_. Note that $`I \div J` is *not* a quotient of $`A`-modules (for example, $`\mathbb{Z} \div \mathbb{Z} = \mathbb{Z}` but $`\mathbb{Z}/\mathbb{Z} = \{0\}`).

We do not assume $`I \subseteq J` (or $`J \subseteq I`), the definition makes sense for any fractional ideals $`I` and $`J` with $`J` nonzero.$^2$ If $`I = (x)` and $`J = (y)` are principal fractional ideals then $`(I \div J) = (x/y)`, so colon ideals can be viewed as a generalization of division in $`K^\times`.

```lean
section FractionalIdealOps

variable {A : Type*} [CommRing A] [IsDomain A]
  [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### Claim 1: Addition of fractional ideals

I + J := {i + j : i ∈ I, j ∈ J}

In Mathlib, addition of fractional ideals is defined
as the supremum (join) in the submodule lattice. The
membership characterization is:
x ∈ I + J ↔ ∃ i ∈ I, ∃ j ∈ J, i + j = x -/

-- Addition is the lattice join
recall FractionalIdeal.sup_eq_add

-- Membership characterization:
-- x ∈ I + J ↔ ∃ i ∈ I, ∃ j ∈ J, i + j = x
recall FractionalIdeal.mem_add

/-! ### Claim 2: Multiplication of fractional ideals

IJ := A-module generated by {ij : i ∈ I, j ∈ J}

In Mathlib, multiplication is defined via the
underlying submodule multiplication, which is the
span of pairwise products. -/

-- i ∈ I, j ∈ J implies i * j ∈ I * J
recall FractionalIdeal.mul_mem_mul

-- I * J ≤ K ↔ ∀ i ∈ I, ∀ j ∈ J, i * j ∈ K
recall FractionalIdeal.mul_le

/-! ### Claim 3: Quotient (colon) ideal

I ÷ J := {x ∈ K : xJ ⊆ I}

In Mathlib, this is `FractionalIdeal / J` using the
submodule division. The membership characterization
is: x ∈ I / J ↔ ∀ y ∈ J, x * y ∈ I. -/

-- The membership characterization of I / J
recall FractionalIdeal.mem_div_iff_of_ne_zero

-- I ÷ J is a fractional ideal (when J ≠ 0)
recall FractionalIdeal.isFractional_div_of_ne_zero

-- The lattice characterization:
-- I ≤ J / J' ↔ I * J' ≤ J
recall FractionalIdeal.le_div_iff_mul_le

/-! ### Claim 4: I ÷ J is NOT a module quotient

The book emphasizes: "I ÷ J is *not* a quotient of
A-modules (for example, ℤ ÷ ℤ = ℤ but
ℤ/ℤ = {0})."

This is a conceptual remark — the notation I ÷ J
(colon ideal) vs I/J (module quotient) refer to
completely different operations. No Lean statement
needed beyond the documentation. -/

/-! ### Claim 5: For principal fractional ideals,
(x) ÷ (y) = (x/y)

This generalizes division in K×. -/

-- (x) / (y) = (x / y) for elements of the fraction
-- field
recall
  FractionalIdeal.spanSingleton_div_spanSingleton

-- Self-division: (x) / (x) = 1 for x ≠ 0
recall FractionalIdeal.spanSingleton_div_self

end FractionalIdealOps
```

# Lemma 2.18
%%%
number := false
%%%

_Lemma 2.18._ _Let $`I` and $`J` be fractional ideals of a noetherian domain $`A` with $`J` nonzero. Then $`(I \div J)` is a fractional ideal of $`A`._

_Proof._ It is clear from the definition that $`I \div J` is closed under addition and multiplication by elements of $`A` (since $`I` is), so $`I \div J` is an $`A`-module of the fraction field of $`A`. To show that $`I \div J` is finitely generated, we first suppose that $`I, J \subseteq A` are ideals. For any nonzero $`j \in J \subseteq A` we have $`j(I \div J) \subseteq I \subseteq A`, so $`(I \div J)` is finitely generated, by Lemma 2.14. For the general case, choose $`a` and $`b` so that $`aI \subseteq A` and $`bJ \subseteq A` via Lemma 2.14. Then $`I \div J = abI \div abJ` with $`abI, abJ \subseteq A`, which we have already shown is finitely generated. $`\square`

```lean
section Lemma_2_18

variable {A : Type*} [CommRing A] [IsDomain A]
  [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### The IsFractional predicate for I / J

This is the core of Lemma 2.18: proving that the
submodule I / J satisfies the IsFractional predicate
when J ≠ 0. -/

-- The underlying proof: IsFractional is preserved
-- by submodule division
#check @IsFractional.div_of_nonzero

-- Specialized to FractionalIdeal: I / J is
-- fractional
#check @FractionalIdeal.isFractional_div_of_ne_zero

/-! ### The Div instance

Mathlib constructs the division I / J as a
FractionalIdeal directly, using the proof above.
This makes I / J well-typed as a
FractionalIdeal. -/

-- I / J returns a FractionalIdeal (0 if J = 0)
#check (inferInstance :
  Div (FractionalIdeal (nonZeroDivisors A) K))

-- The coercion: ↑(I / J) = ↑I / ↑J as submodules
#check @FractionalIdeal.coe_div

/-! ### Lemma 2.18 as an explicit theorem

We state it in a form matching the book: for
noetherian A, the quotient I ÷ J is a fractional
ideal (i.e., finitely generated as an
A-module). -/

/-- **Lemma 2.18**: For fractional ideals I, J of a
noetherian domain A with J nonzero, I ÷ J is a
fractional ideal. In Mathlib this is witnessed by
the fact that `I / J` has type
`FractionalIdeal A⁰ K`, and the underlying
submodule is finitely generated by
`fg_of_isNoetherianRing`. -/
theorem quotient_fractionalIdeal_fg
    (I J : FractionalIdeal
      (nonZeroDivisors A) K)
    (_hJ : J ≠ 0) :
    Submodule.FG
      (↑(I / J) : Submodule A K) :=
  fg_of_isNoetherianRing le_rfl (I / J)

/-! ### Key properties of the quotient

These are used in later results about invertibility
(Lemma 2.20, etc.). -/

-- Membership: x ∈ I / J ↔ ∀ y ∈ J, x * y ∈ I
#check @FractionalIdeal.mem_div_iff_of_ne_zero

-- Lattice characterization:
-- I ≤ J / J' ↔ I * J' ≤ J
#check @FractionalIdeal.le_div_iff_mul_le

end Lemma_2_18
```

# Definition 2.19
%%%
number := false
%%%

_Definition 2.19._ A fractional ideal $`I` is _invertible_ if $`IJ = A` for some fractional ideal $`J`.

Inverses are unique when they exist: if $`IJ = A = IJ'` then $`J = JA = JIJ' = AJ' = J'`. We may use $`I^{-1}` to denote the inverse of a fractional ideal $`I` when it exists.

```lean
section InvertibleFractionalIdeal

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### The definition

_Definition 2.19._ A fractional ideal I is
invertible if IJ = A for some fractional ideal J.
In Mathlib, invertibility is expressed via
`IsUnit I` or equivalently `I * I⁻¹ = 1`. -/

-- I⁻¹ is defined as 1 / I
#check @FractionalIdeal.inv_eq
  -- I⁻¹ = 1 / I

-- I * I⁻¹ = 1 iff I is invertible
-- (i.e. ∃ J, IJ = 1)
#check @FractionalIdeal.mul_inv_cancel_iff
  -- I * I⁻¹ = 1 ↔ ∃ J, I * J = 1

-- Invertibility ↔ IsUnit
#check @FractionalIdeal.mul_inv_cancel_iff_isUnit
  -- I * I⁻¹ = 1 ↔ IsUnit I

/-! ### Uniqueness of inverses

The book proves: if IJ = A = IJ' then
J = JA = JIJ' = AJ' = J'.
In Mathlib, this is captured by
`right_inverse_eq`. -/

-- If I * J = 1 then J = I⁻¹
#check @FractionalIdeal.right_inverse_eq
  -- I * J = 1 → J = I⁻¹

/-! ### Membership in the inverse -/

-- x ∈ I⁻¹ ↔ ∀ y ∈ I, xy ∈ A
-- (i.e., I⁻¹ = {x ∈ K : xI ⊆ A})
#check @FractionalIdeal.mem_inv_iff
  -- I ≠ 0 → (x ∈ I⁻¹ ↔ ∀ y ∈ I, x * y ∈ 1)

/-! ### Monotonicity of inversion -/

-- I ≤ J → J⁻¹ ≤ I⁻¹ (for nonzero ideals)
#check @FractionalIdeal.inv_anti_mono
  -- I ≠ 0 → J ≠ 0 → I ≤ J → J⁻¹ ≤ I⁻¹

/-! ### In Dedekind domains, all nonzero fractional
ideals are invertible

This is the key result connecting Definition 2.19
to the theory of Dedekind domains developed later
in the lecture. -/

section Dedekind

variable [IsDedekindDomain A]

-- In a Dedekind domain, every nonzero fractional
-- ideal is a unit
example
    (I : FractionalIdeal (nonZeroDivisors A) K)
    (hI : I ≠ 0) : IsUnit I :=
  (mul_inv_cancel_iff_isUnit K).mp
    (mul_inv_cancel₀ hI)

end Dedekind

end InvertibleFractionalIdeal
```

# Lemma 2.20
%%%
number := false
%%%

_Lemma 2.20._ _A fractional ideal $`I` of $`A` is invertible if and only if $`I(A \div I) = A` (in which case $`A \div I` is its inverse)._

Before proving the lemma, note that $`I(A \div I) \subseteq A` always holds, since for $`y \in I` and $`x \in A \div I` we have $`xy \in xI \subseteq A`, by the definition of $`A \div I`. The lemma states that this inclusion is an equality precisely when $`I` is invertible.

---

$^2$The definition still makes sense when $`J` is the zero ideal, but $`I \div (0) = K` will typically not be finitely generated as an $`A`-module, hence not a fractional ideal.

_Proof._ Suppose $`I` is invertible, with $`IJ = A`. Then $`jI \subseteq A` for all $`j \in J`, so $`J \subseteq A \div I`, and $`A = IJ \subseteq I(A \div I) \subseteq A`, so $`I(A \div I) = A`. The reverse implication is immediate. $`\square`

```lean
section Lemma_02_20

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### Claim 1: I · I⁻¹ ⊆ 1 always holds

Before the proof, the book notes that
I(A ÷ I) ⊆ A always holds.
In Mathlib, I⁻¹ = 1/I = A ÷ I, so this is
I * I⁻¹ ≤ 1. -/

/-- For any fractional ideal I, we have
I * I⁻¹ ≤ 1 (i.e. I(A ÷ I) ⊆ A). This is because
for x ∈ A ÷ I and y ∈ I, xy ∈ A by
definition. -/
theorem fractionalIdeal_mul_inv_le_one
    (I : FractionalIdeal
      (nonZeroDivisors A) K) :
    I * I⁻¹ ≤ 1 := by
  rw [FractionalIdeal.inv_eq]
  exact FractionalIdeal.mul_one_div_le_one

/-! ### Claim 2: I invertible ↔ I · I⁻¹ = 1

This is the heart of Lemma 2.20: the inclusion
I(A ÷ I) ⊆ A is an equality precisely when I is
invertible. -/

-- I * I⁻¹ = 1 ↔ ∃ J, I * J = 1
recall FractionalIdeal.mul_inv_cancel_iff

/-! ### Claim 3: I⁻¹ = 1 / I

The inverse is the ideal quotient A ÷ I. -/

-- I⁻¹ = 1 / I
recall FractionalIdeal.inv_eq

end Lemma_02_20
```

In the next lecture we will prove that in a Dedekind domain every nonzero fractional ideal is invertible, but let us first note that this is not true in general.

```lean
section Discussion_02_20a

/-! ### Claim 1: Dedekind domains have all nonzero
fractional ideals invertible

This is a forward reference to a result proved in
the next lecture. In Mathlib, this is available as
`FractionalIdeal.mul_inv_cancel₀`. -/

variable {A : Type*} [CommRing A] [IsDomain A]
  [IsDedekindDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-- In a Dedekind domain, every nonzero fractional
ideal satisfies I · I⁻¹ = 1. -/
example
    (I : FractionalIdeal (nonZeroDivisors A) K)
    (hI : I ≠ 0) :
    I * I⁻¹ = 1 :=
  mul_inv_cancel₀ hI

/-! ### Claim 2: Not true in general

The book states this is not true in general. We
exhibit a concrete counterexample: in k[x,y], the
ideal (x,y) is not invertible. This is witnessed by
the fact that k[x,y] is not a Dedekind domain (it
has Krull dimension 2). We state the existence of
non-invertible fractional ideals in non-Dedekind
domains as a sorry'd theorem. -/

/-- There exist domains with non-invertible nonzero
fractional ideals.

We use Polynomial ℤ, which is not a Dedekind domain
(it has Krull dimension 2), so by
`isDedekindDomain_iff_isDedekindDomainInv` there
must exist a non-invertible nonzero fractional
ideal. -/
theorem exists_noninvertible_fractionalIdeal :
    ∃ (A : Type) (_ : CommRing A) (_ : IsDomain A)
      (K : Type) (_ : Field K)
      (_ : Algebra A K) (_ : IsFractionRing A K)
      (I : FractionalIdeal
        (nonZeroDivisors A) K),
      I ≠ 0 ∧ ¬IsUnit I := by
  refine ⟨Polynomial ℤ, inferInstance,
    inferInstance,
    FractionRing (Polynomial ℤ),
    inferInstance, inferInstance, inferInstance,
    ?_⟩
  -- Polynomial ℤ is not a Dedekind domain:
  -- (X) is prime but not maximal
  have hNotDedekind :
      ¬ IsDedekindDomain (Polynomial ℤ) := by
    intro h
    -- (X) is prime and nonzero
    have hXprime :
        (Ideal.span
          {(Polynomial.X :
            Polynomial ℤ)}).IsPrime :=
      (Ideal.span_singleton_prime
        Polynomial.X_ne_zero).mpr
          Polynomial.prime_X
    have hXbot :
        Ideal.span
          {(Polynomial.X :
            Polynomial ℤ)} ≠ ⊥ :=
      Ideal.span_singleton_eq_bot.not.mpr
        Polynomial.X_ne_zero
    -- DimensionLEOne says (X) is maximal
    have hXmax :
        (Ideal.span
          {(Polynomial.X :
            Polynomial ℤ)}).IsMaximal :=
      hXprime.isMaximal hXbot
    -- But Polynomial ℤ/(X) ≅ ℤ, and ℤ is not a
    -- field
    rw [Ideal.Quotient.maximal_ideal_iff_isField_quotient]
      at hXmax
    have :
        Ideal.span
          {(Polynomial.X : Polynomial ℤ)} =
        Ideal.span
          {Polynomial.X -
            Polynomial.C (0 : ℤ)} := by
      simp
    exact Int.not_isField
      ((Polynomial.quotientSpanXSubCAlgEquiv
        (R := ℤ) 0).symm.toMulEquiv.isField
          (this ▸ hXmax))
  -- From ¬ IsDedekindDomain, get
  -- ¬ IsDedekindDomainInv via the iff
  have hNotInv :
      ¬ IsDedekindDomainInv (Polynomial ℤ) :=
    mt isDedekindDomain_iff_isDedekindDomainInv.mpr
      hNotDedekind
  -- Extract the non-invertible fractional ideal
  simp only [IsDedekindDomainInv, not_forall,
    exists_prop] at hNotInv
  obtain ⟨I, hI_ne, hI_not_inv⟩ := hNotInv
  exact ⟨I, hI_ne, fun h => hI_not_inv
    ((FractionalIdeal.mul_inv_cancel_iff_isUnit
      (K := FractionRing (Polynomial ℤ))).mpr
        h)⟩

end Discussion_02_20a
```

# Example 2.21
%%%
number := false
%%%

_Example 2.21._ Consider the subring $`A := \mathbb{Z} + 2i\mathbb{Z}` of the Gaussian integers (with $`i^2 = -1`). The set $`I := 2\mathbb{Z}[i]` is a non-invertible $`A`-ideal (even though it is an invertible $`\mathbb{Z}[i]`-ideal); indeed, we have $`A \div I = \mathbb{Z}[i]` and $`I(A \div I) = 2\mathbb{Z}[i] \subsetneq A`.

```lean
-- `show` used functionally to unfold subtype
-- coercions
set_option linter.style.show false

local notation "ℤ[i]" => GaussianInt

/-! ## The subring A = ℤ + 2iℤ

A consists of Gaussian integers whose imaginary
part is even.
-/

/-- The subring A = ℤ + 2iℤ ⊂ ℤ[i], consisting of
Gaussian integers with even imaginary part. -/
def SubringA : Subring ℤ[i] where
  carrier := {z : ℤ[i] | Even z.im}
  mul_mem' := by
    intro a b ⟨m, hm⟩ ⟨n, hn⟩
    exact ⟨a.re * n + m * b.re,
      by rw [Zsqrtd.im_mul, hm, hn]; ring⟩
  one_mem' := ⟨0, by simp⟩
  add_mem' := fun ha hb => ha.add hb
  zero_mem' := ⟨0, by simp⟩
  neg_mem' := fun ha => ha.neg

/-! ## The set I = 2ℤ[i]

As a subset of ℤ[i],
I = {2a + 2bi : a, b ∈ ℤ}
  = {z ∈ ℤ[i] : Even z.re ∧ Even z.im}.
-/

/-- The set I = 2ℤ[i]: all Gaussian integers with
both real and imaginary parts even. -/
def idealI : Set ℤ[i] :=
  {z : ℤ[i] | Even z.re ∧ Even z.im}

/-- I = 2ℤ[i] is contained in A = ℤ + 2iℤ (since
even im part). -/
theorem idealI_subset_SubringA :
    idealI ⊆ (SubringA : Set ℤ[i]) :=
  fun _ ⟨_, hz_im⟩ => hz_im

/-! ## Claim (a): A = ℤ + 2iℤ is a subring of ℤ[i]

This is established by the definition `SubringA`
above.
-/

/-! ## Claim (b): I = 2ℤ[i] is an ideal of A

We formalize I as an `Ideal SubringA`. Every element
of I has both parts even, so it lies in A. And I is
closed under multiplication by elements of A.
-/

/-- I = 2ℤ[i] as an ideal of the subring A. -/
def idealI_of_A : Ideal SubringA where
  carrier :=
    {z : SubringA | Even z.1.re ∧ Even z.1.im}
  add_mem' := by
    intro ⟨a, _⟩ ⟨b, _⟩ ⟨har, hai⟩ ⟨hbr, hbi⟩
    exact ⟨har.add hbr, hai.add hbi⟩
  zero_mem' := ⟨⟨0, by simp⟩, ⟨0, by simp⟩⟩
  smul_mem' := by
    intro ⟨c, hc_mem⟩ ⟨x, _⟩ ⟨hxr, hxi⟩
    obtain ⟨m, hm⟩ := hxr
    obtain ⟨n, hn⟩ := hxi
    obtain ⟨p, hp⟩ := hc_mem
    show Even (c * x).re ∧ Even (c * x).im
    exact
      ⟨⟨c.re * m - p * x.im,
        by rw [Zsqrtd.re_mul, hm, hp]; ring⟩,
       ⟨c.re * n + p * x.re,
        by rw [Zsqrtd.im_mul, hn, hp]; ring⟩⟩

/-! ## Claim (c): I is invertible as a ℤ[i]-ideal

As a ℤ[i]-ideal, I = (2) is principal, hence
invertible.
-/

/-- I = 2ℤ[i] as an ideal of ℤ[i], i.e., the
principal ideal (2). -/
def idealI_of_ZI : Ideal ℤ[i] :=
  Ideal.span {(⟨2, 0⟩ : ℤ[i])}

/-- I = (2) is a nonzero ideal of ℤ[i]. Combined
with the fact that ℤ[i] is a PID (and hence a
Dedekind domain), this implies I is invertible as a
fractional ideal. -/
theorem idealI_of_ZI_ne_bot :
    idealI_of_ZI ≠ ⊥ := by
  rw [idealI_of_ZI, Ne,
    Ideal.span_singleton_eq_bot]
  simp [Zsqrtd.ext_iff]

/-- ℤ[i] is a principal ideal ring (hence every
nonzero ideal is invertible). -/
instance : IsPrincipalIdealRing ℤ[i] :=
  EuclideanDomain.to_principal_ideal_domain

/-! ## Claim (d): A ÷ I = ℤ[i]

The conductor of I in A equals all of ℤ[i].
Concretely, for every z ∈ ℤ[i], z · I ⊆ A. This
is because if w ∈ I = 2ℤ[i] then
z * w = 2(z * w') ∈ 2ℤ[i] ⊆ A.
-/

/-- For all z ∈ ℤ[i] and w ∈ I, we have z * w ∈ A.
This shows A ÷ I = ℤ[i]. -/
theorem conductor_eq_full :
    ∀ (z : ℤ[i]) (w : ℤ[i]),
      w ∈ idealI →
        (z * w) ∈ (SubringA : Set ℤ[i]) := by
  intro z w ⟨⟨m, hm⟩, ⟨n, hn⟩⟩
  show Even (z * w).im
  exact ⟨z.re * n + z.im * m,
    by rw [Zsqrtd.im_mul, hm, hn]; ring⟩

/-! ## Claim (e): I is NOT invertible as an A-ideal

I(A ÷ I) = I · ℤ[i] = 2ℤ[i] = I ⊊ A, so I fails
the invertibility condition.
-/

/-- 2ℤ[i] is strictly contained in A = ℤ + 2iℤ
(e.g., 1 ∈ A but 1 ∉ 2ℤ[i]). -/
theorem idealI_ssubset_SubringA :
    idealI ⊂ (SubringA : Set ℤ[i]) := by
  refine ⟨idealI_subset_SubringA, ?_⟩
  intro h
  have h1 : (1 : ℤ[i]) ∈
      (SubringA : Set ℤ[i]) :=
    SubringA.one_mem
  have h2 : (1 : ℤ[i]) ∈ idealI := h h1
  simp only [idealI, Set.mem_setOf_eq] at h2
  obtain ⟨⟨r, hr⟩, _⟩ := h2
  -- hr : (1 : ℤ[i]).re = r + r, i.e. 1 = 2r,
  -- impossible in ℤ
  simp at hr; omega

/-- I is not invertible as an A-ideal: the product
I · (A ÷ I) = I ≠ A. -/
theorem idealI_not_invertible_over_A :
    idealI ≠ (SubringA : Set ℤ[i]) :=
  idealI_ssubset_SubringA.ne
```

In this section $`A` is a noetherian domain (not necessarily a Dedekind domain) and $`K` is its fraction field. Recall that a fractional ideal of $`A` is a finitely generated $`A`-submodule of $`K`, and if $`I` and $`J` are fractional ideals, so is the ideal quotient

$$`I \div J := \{x \in K : xJ \subseteq I\},`

and we say that a fractional ideal $`I` is invertible if $`IJ = A` for some fractional ideal $`J`. The definition of $`A \div I` implies $`I(A \div I) \subseteq A`, and Lemma 2.20 implies that $`I` is invertible precisely when this inclusion is an equality, in which case the inverse of $`I` is $`A \div I`.

Ideal multiplication is commutative and associative, thus the set of nonzero fractional ideals of a noetherian domain form an abelian monoid under multiplication with $`A = (1)` as the identity. It follows that the subset of invertible fractional ideals is an abelian group.

```lean
section Discussion_02_21a

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]

open FractionalIdeal

/-! ### Claim 1: I invertible iff I(A÷I) = A

This is a back-reference to Lemma 2.20. -/

-- I * I⁻¹ = 1 ↔ ∃ J, I * J = 1
recall FractionalIdeal.mul_inv_cancel_iff

/-! ### Claim 2: Nonzero fractional ideals form an
abelian monoid

Ideal multiplication is commutative and
associative, with A = (1) as identity. In Mathlib,
`FractionalIdeal` carries a `CommMonoidWithZero`
instance (the zero ideal is absorbing, and nonzero
ideals form a commutative monoid). -/

-- FractionalIdeal carries a CommSemiring (hence
-- CommMonoidWithZero) structure
example :
    CommSemiring
      (FractionalIdeal (nonZeroDivisors A) K) :=
  inferInstance

/-! ### Claim 3: Invertible fractional ideals form an
abelian group

The units of any commutative monoid form an abelian
group. In Lean 4,
`(FractionalIdeal (nonZeroDivisors A) K)ˣ` is the
type of invertible fractional ideals, which inherits
a `CommGroup` structure. -/

-- Units of a CommMonoid form a CommGroup
example :
    CommGroup
      (FractionalIdeal
        (nonZeroDivisors A) K)ˣ :=
  inferInstance

end Discussion_02_21a
```
