import VersoManual
import Mathlib.Tactic.Recall
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Localization.Module
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.DedekindDomain.Basic
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.LocalRing.ResidueField.Basic
import Mathlib.RingTheory.Localization.Submodule
import Mathlib.Algebra.Polynomial.Eval.SMul
import Mathlib.Algebra.Polynomial.FieldDivision
import Mathlib.RingTheory.Polynomial.Quotient
import Mathlib.NumberTheory.Padics.PadicVal.Basic
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.RingTheory.Ideal.NatInt
import SutherlandNumberTheory.Lecture2.Localization

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option verso.code.warnLineLength 90

#doc (Manual) "Localization of Modules" =>
%%%
tag := "localization-of-modules"
file := some "localization-of-modules"
number := false
%%%

# Example 2.4
%%%
number := false
%%%

_Example 2.4._ For a field $`k`, let $`A = k[x]` and $`\mathfrak{p} = (x - 2)`. Then

$$`A_{\mathfrak{p}} = \{f \in k(x) : f \text{ is defined at } 2\}.`

The ring $`A` is a PID, so $`A_{\mathfrak{p}}` is a PID with a unique nonzero maximal ideal (the ideal $`\mathfrak{p}A_{\mathfrak{p}}`), hence a DVR. Its maximal ideal is

$$`\mathfrak{p}A_{\mathfrak{p}} = \{f \in k(x) : f(2) = 0\}.`

The valuation on the field $`k(x) = \operatorname{Frac} A` corresponding to the valuation ring $`A_{\mathfrak{p}}` measures the order of vanishing of functions $`f \in k(x)` at $`2`. The residue field is $`A_{\mathfrak{p}}/\mathfrak{p}A_{\mathfrak{p}} \simeq k`, and the quotient map $`A_{\mathfrak{p}} \twoheadrightarrow A_{\mathfrak{p}}/\mathfrak{p}A_{\mathfrak{p}}` sends $`f` to $`f(2)`.

```lean
open Polynomial

section Example_2_4

variable (k : Type*) [Field k]

/-! ### The prime ideal (x - 2) in k[x]

The ideal generated by (X - C 2) in k[x] is prime
because X - C 2 is irreducible
(it has degree 1). -/

/-- The prime ideal 𝔭 = (x - 2) in k[x]. -/
noncomputable def polyPrimeIdeal_x_sub_2 :
    Ideal k[X] :=
  Ideal.span {X - C 2}

/-- (x - 2) is a prime element in k[x]. -/
theorem x_sub_2_prime :
    Prime (X - C 2 : k[X]) :=
  Polynomial.prime_of_degree_eq_one
    (by simp [Polynomial.degree_X_sub_C])

/-- The ideal (x - 2) is a prime ideal in
k[x]. -/
instance polyPrimeIdeal_x_sub_2_isPrime :
    (polyPrimeIdeal_x_sub_2 k).IsPrime := by
  rw [polyPrimeIdeal_x_sub_2,
    Ideal.span_singleton_prime
      (X_sub_C_ne_zero 2)]
  exact x_sub_2_prime k

/-! ### The localization k[x]_(x-2)

The localization of k[x] at the prime ideal
(x - 2). -/

/-- k[x]_(x-2): the localization of k[x] at the
prime ideal (x - 2). -/
noncomputable abbrev kx_loc_x_sub_2 : Type _ :=
  Localization.AtPrime (polyPrimeIdeal_x_sub_2 k)

/-! ### k[x] is a PID

This is a standard Mathlib fact: polynomial rings
over fields are PIDs.
Since PIDs are Dedekind domains, we get the DVR
result from Mathlib's
`IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain`. -/

-- k[x] is a PID
#check (inferInstance :
  IsPrincipalIdealRing k[X])

-- PID → Dedekind domain (Mathlib instance)
#check @IsPrincipalIdealRing.isDedekindDomain

-- Localization of Dedekind domain at nonzero
-- prime → DVR
#check
  @IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain

/-! ### k[x]_(x-2) is a DVR

The key result: since k[x] is a PID (hence
Dedekind domain), and (x-2) is a nonzero prime
ideal, the localization k[x]_(x-2) is a DVR. -/

/-- (x - 2) ≠ 0 in k[x], so the ideal (x-2) is
nonzero (i.e., ⊥ < 𝔭). -/
theorem polyPrimeIdeal_x_sub_2_ne_bot :
    polyPrimeIdeal_x_sub_2 k ≠ ⊥ := by
  rw [polyPrimeIdeal_x_sub_2, Ne,
    Ideal.span_singleton_eq_bot]
  exact X_sub_C_ne_zero 2

/-- k[x]_(x-2) is a DVR (Example 2.4).
Proof: k[x] is a PID → Dedekind domain.
Localization of a Dedekind domain
at a nonzero prime ideal is a DVR. -/
instance kx_loc_x_sub_2_isDVR :
    IsDiscreteValuationRing
      (kx_loc_x_sub_2 k) :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
    k[X] (polyPrimeIdeal_x_sub_2_ne_bot k)
    (kx_loc_x_sub_2 k)

/-! ### Maximal ideal characterization

The maximal ideal of k[x]_(x-2) is the extension
of (x-2) to the localization.
It consists of rational functions that vanish
at 2. -/

/-- The maximal ideal of k[x]_(x-2) is the
extension of (x-2) to the localization.
This is the unique nonzero maximal ideal of the
DVR. -/
theorem kx_loc_x_sub_2_maximalIdeal :
    IsLocalRing.maximalIdeal
      (kx_loc_x_sub_2 k) =
      (polyPrimeIdeal_x_sub_2 k).map
        (algebraMap k[X]
          (kx_loc_x_sub_2 k)) := by
  exact
    Localization.AtPrime.map_eq_maximalIdeal.symm

/-! ### Residue field

The residue field of k[x]_(x-2) is isomorphic
to k. The quotient map sends f to f(2).
This follows because the residue field of a
localization at a prime 𝔭 generated by
a degree-1 polynomial over a field k is k
itself. -/

/-- (x - 2) is a maximal ideal in k[x] (since
k[x] is a PID and x-2 is irreducible). -/
instance polyPrimeIdeal_x_sub_2_isMaximal :
    (polyPrimeIdeal_x_sub_2 k).IsMaximal :=
  Ideal.IsPrime.isMaximal inferInstance
    (polyPrimeIdeal_x_sub_2_ne_bot k)

/-- The residue field of k[x]_(x-2) is
isomorphic to k. -/
theorem kx_loc_x_sub_2_residueField :
    Nonempty
      (IsLocalRing.ResidueField
        (kx_loc_x_sub_2 k) ≃+* k) := by
  -- ResidueField(k[x]_(x-2)) ≃ k[X]/(X-2) ≃ k
  have e1 : k[X] ⧸ polyPrimeIdeal_x_sub_2 k ≃+*
      IsLocalRing.ResidueField
        (kx_loc_x_sub_2 k) :=
    IsLocalization.AtPrime.equivQuotMaximalIdeal
      (polyPrimeIdeal_x_sub_2 k)
      (kx_loc_x_sub_2 k)
  have e2 : (k[X] ⧸
      Ideal.span
        ({X - C 2} : Set k[X])) ≃+* k :=
    (Polynomial.quotientSpanXSubCAlgEquiv
      (R := k) 2).toRingEquiv
  exact ⟨e1.symm.trans e2⟩

/-- The quotient map k[x]_(x-2) → k sends f to
its evaluation at 2.
More precisely, the composition
k[x] → k[x]_(x-2) → residue field ≃ k
agrees with evaluation at 2. -/
theorem kx_loc_x_sub_2_quotientMap_eq_eval :
    ∀ f : k[X],
      IsLocalRing.residue (kx_loc_x_sub_2 k)
        (algebraMap k[X]
          (kx_loc_x_sub_2 k) f) =
      algebraMap k
        (IsLocalRing.ResidueField
          (kx_loc_x_sub_2 k))
        (Polynomial.eval 2 f) := by
  intro f
  -- f - C(eval 2 f) is divisible by (X - C 2),
  -- hence in 𝔭
  have hmem :
      f - C (Polynomial.eval 2 f) ∈
        polyPrimeIdeal_x_sub_2 k := by
    rw [polyPrimeIdeal_x_sub_2,
      Ideal.mem_span_singleton]
    exact dvd_iff_isRoot.mpr (by simp [IsRoot])
  -- So its image under algebraMap is in the
  -- maximal ideal, killed by residue
  have hzero :
      IsLocalRing.residue (kx_loc_x_sub_2 k)
        (algebraMap k[X] (kx_loc_x_sub_2 k)
          (f - C (Polynomial.eval 2 f))) =
        0 := by
    rw [IsLocalRing.residue_eq_zero_iff,
      kx_loc_x_sub_2_maximalIdeal]
    exact Ideal.mem_map_of_mem _ hmem
  -- Expand and rearrange to get
  -- residue(algebraMap f)
  --   = residue(algebraMap(C(eval 2 f)))
  rw [map_sub] at hzero
  rw [map_sub] at hzero
  have hzero' := sub_eq_zero.mp hzero
  rw [hzero']
  -- Goal: residue(algebraMap(C(eval 2 f)))
  --   = algebraMap k ResidueField (eval 2 f)
  -- This follows from the scalar tower
  -- k → k[X] → loc → ResidueField
  -- Goal: residue(algebraMap_{k[X]}(C(eval 2 f)))
  --   = residue(algebraMap_{k}(eval 2 f))
  -- C a = algebraMap k k[X] a, and scalar tower
  -- gives the rest
  rw [Polynomial.C_eq_algebraMap,
    ← IsScalarTower.algebraMap_apply k k[X]
      (kx_loc_x_sub_2 k),
    IsScalarTower.algebraMap_apply k
      (kx_loc_x_sub_2 k)
      (IsLocalRing.ResidueField
        (kx_loc_x_sub_2 k)),
    IsLocalRing.ResidueField.algebraMap_eq]

end Example_2_4
```

# Example 2.5
%%%
number := false
%%%

_Example 2.5._ Let $`p \in \mathbb{Z}` be a prime. Then $`\mathbb{Z}_{(p)} = \{a/b : a, b \in \mathbb{Z}, p \nmid b\}`. As in the previous example, $`\mathbb{Z}` is a PID and $`\mathbb{Z}_{(p)}` is a DVR; the valuation on $`\mathbb{Q}` is the $`p`-adic valuation. The residue field is $`\mathbb{Z}_{(p)}/p\mathbb{Z}_{(p)} \simeq \mathbb{F}_p` and the quotient map $`\mathbb{Z}_{(p)} \twoheadrightarrow \mathbb{F}_p` is reduction modulo $`p`.

```lean
section Example_2_5

/-! ### The prime ideal (p) in ℤ

The ideal generated by a prime p in ℤ is a prime
ideal (see Lecture 1, Example 1.14). -/

/-! ### The localization ℤ_(p)

ℤ_(p) = {a/b : a, b ∈ ℤ, p ∤ b} is the
localization of ℤ at the prime ideal (p).
Lecture 1 (Example 1.14) shows this is a local
ring. -/

variable (p : ℕ) [hp : Fact p.Prime]

/-- The prime ideal (p) in ℤ. -/
noncomputable def intPrimeIdeal_p : Ideal ℤ :=
  Ideal.span {(p : ℤ)}

/-- (p) is a prime ideal in ℤ. -/
instance intPrimeIdeal_p_isPrime :
    (intPrimeIdeal_p p).IsPrime := by
  rw [intPrimeIdeal_p,
    Ideal.span_singleton_prime
      (by exact_mod_cast hp.out.ne_zero)]
  exact Nat.prime_iff_prime_int.mp hp.out

/-- ℤ_(p): the localization of ℤ at the prime
ideal (p). -/
noncomputable abbrev Z_loc_p : Type :=
  Localization.AtPrime (intPrimeIdeal_p p)

-- ℤ_(p) is a local ring (automatic from
-- localization at a prime)
example : IsLocalRing (Z_loc_p p) := inferInstance

/-! ### ℤ is a PID

This is a standard Mathlib fact. Since PIDs are
Dedekind domains, we get the DVR result. -/

-- ℤ is a PID
#check (inferInstance :
  IsPrincipalIdealRing ℤ)

/-! ### ℤ_(p) is a DVR

The key result: since ℤ is a PID (hence Dedekind
domain), and (p) is a nonzero prime ideal, the
localization ℤ_(p) is a DVR. -/

/-- (p) ≠ 0 in ℤ, so the ideal (p) is
nonzero. -/
theorem intPrimeIdeal_p_ne_bot :
    intPrimeIdeal_p p ≠ ⊥ := by
  rw [intPrimeIdeal_p, Ne,
    Ideal.span_singleton_eq_bot]
  exact_mod_cast hp.out.ne_zero

/-- ℤ_(p) is a DVR (Example 2.5).
Proof: ℤ is a PID → Dedekind domain.
Localization of a Dedekind domain
at a nonzero prime ideal is a DVR. -/
instance Z_loc_p_isDVR :
    IsDiscreteValuationRing (Z_loc_p p) :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
    ℤ (intPrimeIdeal_p_ne_bot p) (Z_loc_p p)


/-! ### The p-adic valuation

The valuation on ℚ = Frac(ℤ) corresponding to
the valuation ring ℤ_(p) is the p-adic valuation.
Recall from Lecture 1 (Definition 1.7): -/

-- Recall: p-adic valuation on ℚ
#check @padicValRat

/-! ### Residue field

The residue field is ℤ_(p)/pℤ_(p) ≃ 𝔽_p = ℤ/pℤ,
and the quotient map is reduction modulo p. -/

/-- (p) is a maximal ideal in ℤ (since ℤ is a PID
and p is prime). -/
instance intPrimeIdeal_p_isMaximal :
    (intPrimeIdeal_p p).IsMaximal :=
  Ideal.IsPrime.isMaximal inferInstance
    (intPrimeIdeal_p_ne_bot p)

/-- The residue field of ℤ_(p) is isomorphic to
𝔽_p = ℤ/pℤ. -/
theorem Z_loc_p_residueField :
    Nonempty
      (IsLocalRing.ResidueField (Z_loc_p p)
        ≃+* ZMod p) := by
  -- ResidueField(ℤ_(p)) ≃ ℤ/(p) ≃ ZMod p
  have e1 : ℤ ⧸ intPrimeIdeal_p p ≃+*
      IsLocalRing.ResidueField (Z_loc_p p) :=
    IsLocalization.AtPrime.equivQuotMaximalIdeal
      (intPrimeIdeal_p p) (Z_loc_p p)
  have e2 : ℤ ⧸ Ideal.span {(p : ℤ)} ≃+*
      ZMod (p : ℤ).natAbs :=
    Int.quotientSpanEquivZMod p
  exact ⟨e1.symm.trans
    (e2.trans (ZMod.ringEquivCongr
      (Int.natAbs_natCast p)))⟩

/-- The quotient map ℤ_(p) → residue field, when
composed with the residue field isomorphism to
ZMod p, gives reduction modulo p. That is, for
the isomorphism
φ : ResidueField(ℤ_(p)) ≃+* ZMod p from
`Z_loc_p_residueField`, we have
φ(residue(algebraMap n)) = (n : ZMod p)
for all n : ℤ. -/
theorem Z_loc_p_quotientMap_eq_mod
    (φ : IsLocalRing.ResidueField (Z_loc_p p)
      ≃+* ZMod p) :
    ∀ n : ℤ,
      φ (IsLocalRing.residue (Z_loc_p p)
        (algebraMap ℤ (Z_loc_p p) n)) =
      (n : ZMod p) :=
  fun n => eq_intCast
    (φ.toRingHom.comp
      ((IsLocalRing.residue (Z_loc_p p)).comp
        (algebraMap ℤ (Z_loc_p p)))) n

end Example_2_5
```

The concept of localization generalizes immediately to modules. As above, let $`A` be a commutative ring, let $`S` be a multiplicative subset of $`A`, and let $`M` be an $`A`-module. The localization $`S^{-1}M` of $`M` with respect to $`S` is an $`S^{-1}A`-module equipped with an $`A`-module homomorphism $`\iota\colon M \to S^{-1}M` with the universal property that if $`N` is an $`S^{-1}A`-module and $`\varphi\colon M \to N` is an $`A`-module homomorphism, then $`\varphi` factors uniquely through $`S^{-1}M` (via $`\iota`). Note that in this definition we are viewing $`S^{-1}A`-modules as $`A`-modules via the canonical homomorphism $`A \to S^{-1}A` that is part of the definition of $`S^{-1}A`. Our definition of $`S^{-1}M` reduces to the definition of $`S^{-1}A` in the case $`M = A`.

The explicit construction of $`S^{-1}M` is exactly the same as $`S^{-1}A`, one takes the quotient of $`M \times S` modulo the same equivalence relation as in (1):

$$`(a, s) \sim (b, t) \Leftrightarrow \exists u \in S \text{ such that } u(ta - sb) = 0,`

where $`a` and $`b` now denote elements of $`M`, and $`\iota(a) := a/1` as before. Alternatively, one can define $`S^{-1}M := M \otimes_A S^{-1}A` (see \[2, Prop. 3.5\] for a proof that this is equivalent). In other words, $`S^{-1}M` is the _base change_ of $`M` from $`A` to $`S^{-1}A`; we will discuss base change more generally in later lectures.

The map $`\iota\colon M \to S^{-1}M` is injective if and only if the map $`M \xrightarrow{\times s} M` is injective for every $`s \in S`. This is a strong condition that does not hold in general, even when $`A` is an integral domain (the annihilator of $`M` may be non-trivial), but it applies to all the cases we care about. In particular, if $`A` is a subring of a field $`K` (in which case $`A` must be an integral domain whose fraction field lies in $`K`) and $`M` is an $`A`-module that is contained in a $`K`-vector space. In this setting multiplication by any nonzero $`s \in A` is injective and we can view $`M` as an $`A`-submodule of any of its localizations $`S^{-1}M`.

We will mostly be interested in the case $`S = A - \mathfrak{p}`, where $`\mathfrak{p}` is a prime ideal of $`A`, in which case we write $`M_{\mathfrak{p}}` for $`S^{-1}M`, just as we write $`A_{\mathfrak{p}}` for $`S^{-1}A`.

```lean
section Discussion_02_05a

variable {A : Type*} [CommRing A]
  (S : Submonoid A)
  (M : Type*) [AddCommGroup M] [Module A M]

/-! ### Claim 1: S⁻¹M as a type

The localized module S⁻¹M, with elements
represented as m/s
for m ∈ M, s ∈ S. -/

-- The type S⁻¹M
recall LocalizedModule

-- Constructor m/s for elements of S⁻¹M
recall LocalizedModule.mk

-- The canonical map ι: M → S⁻¹M
recall LocalizedModule.mkLinearMap

/-! ### Claim 2: Universal property of S⁻¹M

S⁻¹M is characterized by the universal property:
if N is an S⁻¹A-module
and φ: M → N is an A-module homomorphism, then φ
factors uniquely through S⁻¹M. -/

-- Typeclass for module localization (captures the
-- universal property)
recall IsLocalizedModule

/-! ### Claim 3: S⁻¹M ≅ M ⊗_A S⁻¹A

The localization of a module can alternatively be
constructed as the
base change (tensor product) M ⊗_A S⁻¹A. -/

-- S⁻¹M ≃ₗ[S⁻¹A] (S⁻¹A) ⊗[A] M
recall LocalizedModule.equivTensorProduct

/-! ### Claim 4: ι injective iff multiplication by
s injective for all s ∈ S

The canonical map ι: M → S⁻¹M is injective if and
only if for every s ∈ S, the multiplication map
(×s): M → M is injective.

The book notes this is a strong condition that does
not hold in general,
but holds when A is a subring of a field and M is
contained in a K-vector space. -/

/-- The canonical map M → S⁻¹M is injective iff
multiplication by every s ∈ S is injective
on M. -/
theorem
    localizedModule_mkLinearMap_injective_iff :
    Function.Injective
      (LocalizedModule.mkLinearMap S M) ↔
      ∀ s : S, Function.Injective
        (HSMul.hSMul (α := A) s.1 :
          M → M) := by
  rw [← LinearMap.ker_eq_bot,
    LinearMap.ker_eq_bot']
  constructor
  · intro h s a b hab
    exact sub_eq_zero.mp <| h _ <|
      LocalizedModule.mem_ker_mkLinearMap_iff.mpr
        ⟨s.1, s.2, by
          rw [smul_sub, hab, sub_self]⟩
  · intro h m hm
    obtain ⟨r, hr, hrm⟩ :=
      LocalizedModule.mem_ker_mkLinearMap_iff.mp
        (LinearMap.mem_ker.mpr hm)
    exact h ⟨r, hr⟩
      (show r • m = r • (0 : M) by
        rwa [smul_zero])

/-! ### Claim 5: Embedding when A is a subring of
a field

If A is a subring of a field K and M is an
A-submodule of a K-vector space,
then multiplication by any nonzero s ∈ A is
injective on M, so ι is injective
and M embeds into S⁻¹M. -/

/-- When A is an integral domain and M is
torsion-free, the canonical map
M → S⁻¹M is injective (the book's "A subring of
a field" case). -/
theorem
    localizedModule_mkLinearMap_injective_of_noZeroSMulDivisors
    [IsDomain A] [NoZeroSMulDivisors A M]
    (hS : ∀ s : S, (s : A) ≠ 0) :
    Function.Injective
      (LocalizedModule.mkLinearMap S M) := by
  rw [localizedModule_mkLinearMap_injective_iff]
  intro s a b hab
  have hsub : s.1 • (a - b) = 0 := by
    rw [smul_sub, hab, sub_self]
  exact sub_eq_zero.mp
    ((smul_eq_zero.mp hsub).resolve_left (hS s))

end Discussion_02_05a
```

# Proposition 2.6
%%%
number := false
%%%

_Proposition 2.6._ _Let $`A` be a subring of a field $`K`, and let $`M` be an $`A`-module contained in a $`K`-vector space $`V` (equivalently, for which the map $`M \to M \otimes_A K` is injective).$^1$ Then_

$$`M = \bigcap_{\mathfrak{m}} M_{\mathfrak{m}} = \bigcap_{\mathfrak{p}} M_{\mathfrak{p}},`

_where $`\mathfrak{m}` ranges over the maximal ideals of $`A`, $`\mathfrak{p}` ranges over the prime ideals of $`A`, and the intersections take place in $`V`._

_Proof._ The fact that $`M \subseteq \bigcap_{\mathfrak{m}} M_{\mathfrak{m}}` is immediate. Now suppose $`x \in \bigcap_{\mathfrak{m}} M_{\mathfrak{m}}` and consider the $`A`-ideal $`\mathfrak{a} := \{a \in A : ax \in M\}`. For each maximal ideal $`\mathfrak{m}` we can write $`x = m/s` for some $`m \in M` and $`s \in A - \mathfrak{m}`; we then have $`sx \in M` and $`s \in \mathfrak{a}`, but $`s \notin \mathfrak{m}`, so $`\mathfrak{a} \nsubseteq \mathfrak{m}`. This holds for every maximal ideal $`\mathfrak{m}`, so $`\mathfrak{a} = (1)`. Thus $`1 \in \mathfrak{a}` and $`x = 1 \cdot x \in M`; thus $`\cap_{\mathfrak{m}} M_{\mathfrak{m}} \subseteq M`.

Each $`\mathfrak{p}` lies in some $`\mathfrak{m}` for which $`M_{\mathfrak{m}} \subseteq M_{\mathfrak{p}}`, and every $`\mathfrak{m}` is a $`\mathfrak{p}`, so $`\cap_{\mathfrak{m}} M_{\mathfrak{m}} = \cap_{\mathfrak{p}} M_{\mathfrak{p}}`. $`\square`

---

$`{}^1`Here $`M \otimes_A K` is a tensor product of $`A`-modules that is also a $`K`-vector space. We need the natural map to be injective in order to embed $`M` in it. Note that $`V` necessarily contains a subspace isomorphic to $`M \otimes_A K`.

```lean
section Proposition_2_6

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K]
  [IsFractionRing A K]
variable {V : Type*} [AddCommGroup V]
  [Module K V] [Module A V]
  [IsScalarTower A K V]

/-! ## Localization of a submodule at a prime

Given M : Submodule A V where V is a K-vector
space, the localization of M at a
prime ideal 𝔭 is
{x ∈ V | ∃ s ∈ A \ 𝔭, s • x ∈ M}. Since V is a
K-vector space and K = Frac(A), this naturally
lives in V. -/

/-- The localization of a submodule M at a prime
ideal 𝔭, viewed as a submodule of the
ambient K-vector space V. An element x ∈ V lies
in M_𝔭 iff there exists s ∈ A \ 𝔭
with s • x ∈ M. -/
def Submodule.localizedAtPrime
    (M : Submodule A V) (𝔭 : Ideal A)
    [𝔭.IsPrime] :
    Submodule A V where
  carrier :=
    { x : V | ∃ s : 𝔭.primeCompl,
        (s : A) • x ∈ M }
  add_mem' := by
    rintro x y ⟨s, hsx⟩ ⟨t, hty⟩
    refine ⟨⟨s * t,
      𝔭.primeCompl.mul_mem s.2 t.2⟩, ?_⟩
    have : (↑s * ↑t : A) • (x + y) =
        (t : A) • ((s : A) • x) +
        (s : A) • ((t : A) • y) := by
      rw [mul_comm (↑s : A) ↑t, mul_smul,
        smul_add, smul_add]
      congr 1
      exact smul_comm (↑t : A) (↑s : A) y
    rw [this]
    exact M.add_mem (M.smul_mem _ hsx)
      (M.smul_mem _ hty)
  zero_mem' :=
    ⟨⟨1, 𝔭.primeCompl.one_mem⟩,
      by simp [M.zero_mem]⟩
  smul_mem' := by
    intro a x ⟨⟨s, hs⟩, hsx⟩
    -- s • x ∈ M, so s • (a • x) = a • (s • x)
    -- ∈ M
    exact ⟨⟨s, hs⟩,
      by rw [smul_comm]; exact M.smul_mem a hsx⟩

omit [IsDomain A] in
/-- M is contained in each of its
localizations. -/
theorem Submodule.le_localizedAtPrime
    (M : Submodule A V) (𝔭 : Ideal A)
    [𝔭.IsPrime] :
    M ≤ M.localizedAtPrime 𝔭 := by
  intro x hx
  exact ⟨⟨1, 𝔭.primeCompl.one_mem⟩,
    by simpa using hx⟩

omit [IsDomain A] in
/-- If 𝔭 ⊆ 𝔮, then M_𝔮 ⊆ M_𝔭 (localizing at a
smaller prime gives a larger module). -/
theorem Submodule.localizedAtPrime_anti
    (M : Submodule A V)
    {𝔭 𝔮 : Ideal A} [𝔭.IsPrime] [𝔮.IsPrime]
    (h : 𝔭 ≤ 𝔮) :
    M.localizedAtPrime 𝔮 ≤
      M.localizedAtPrime 𝔭 := by
  intro x ⟨⟨s, hs⟩, hsx⟩
  -- s ∉ 𝔮 and 𝔭 ⊆ 𝔮 implies s ∉ 𝔭
  exact ⟨⟨s, fun hs𝔭 => hs (h hs𝔭)⟩, hsx⟩

/-! ## The conductor ideal

The proof uses the "conductor" ideal
𝔞 = {a ∈ A | a·x ∈ M} for a fixed x ∈ V.
-/

/-- The conductor of x into M: the ideal
{a ∈ A | a • x ∈ M}. -/
def Submodule.conductor
    (M : Submodule A V) (x : V) :
    Ideal A where
  carrier := { a : A | a • x ∈ M }
  add_mem' ha hb := by
    simp only [Set.mem_setOf_eq, add_smul]
    exact M.add_mem ha hb
  zero_mem' := by simp [M.zero_mem]
  smul_mem' c _ ha := by
    simp only [Set.mem_setOf_eq, smul_eq_mul,
      mul_smul]
    exact M.smul_mem c ha

omit [IsDomain A] in
/-- If x ∈ M_𝔭 then the conductor of x into M is
not contained in 𝔭. -/
theorem
    Submodule.conductor_not_le_of_mem_localizedAtPrime
    (M : Submodule A V) (x : V)
    (𝔭 : Ideal A) [𝔭.IsPrime]
    (hx : x ∈ M.localizedAtPrime 𝔭) :
    ¬(M.conductor x ≤ 𝔭) := by
  obtain ⟨⟨s, hs⟩, hsx⟩ := hx
  intro h
  exact hs (h hsx)

/-! ## The main proposition

**Proof strategy** (from the book): Suppose
x ∈ ⋂_𝔪 M_𝔪. Consider the A-ideal
𝔞 := {a ∈ A | a·x ∈ M}. For each maximal ideal
𝔪, since x ∈ M_𝔪, there exists s ∉ 𝔪 with
s·x ∈ M, so s ∈ 𝔞 and s ∉ 𝔪, hence 𝔞 ⊄ 𝔪.
Since 𝔞 is not contained in any maximal ideal,
𝔞 = A, so 1 ∈ 𝔞 and x = 1·x ∈ M.

For the equality of the two intersections: every
maximal ideal is prime, and every prime is
contained in some maximal ideal with
M_𝔪 ⊆ M_𝔭 when 𝔭 ⊆ 𝔪. -/

omit [IsDomain A] in
/-- **Proposition 2.6** (prime ideals version).
M equals the intersection of its
localizations at all prime ideals:
  M = ⋂_𝔭 M_𝔭
where 𝔭 ranges over prime ideals of A. -/
theorem Submodule.eq_iInf_localizedAtPrime
    (M : Submodule A V) :
    M = ⨅ (𝔭 : Ideal A) (_ : 𝔭.IsPrime),
      M.localizedAtPrime 𝔭 := by
  apply le_antisymm
  · exact le_iInf₂ fun 𝔭 _ =>
      M.le_localizedAtPrime 𝔭
  · intro x hx
    simp only [Submodule.mem_iInf] at hx
    have htop : M.conductor x = ⊤ := by
      by_contra h
      obtain ⟨𝔪, h𝔪, hle⟩ :=
        Ideal.exists_le_maximal _ h
      exact
        M.conductor_not_le_of_mem_localizedAtPrime
          x 𝔪 (hx 𝔪 h𝔪.isPrime) hle
    have h1 : (1 : A) • x ∈ M :=
      show (1 : A) ∈ M.conductor x by
        rw [htop]; trivial
    simpa using h1

omit [IsDomain A] in
/-- **Proposition 2.6** (maximal ideals version).
M equals the intersection of its
localizations at all maximal ideals:
  M = ⋂_𝔪 M_𝔪
where 𝔪 ranges over maximal ideals of A. -/
theorem
    Submodule.eq_iInf_localizedAtPrime_maximal
    (M : Submodule A V) :
    M = ⨅ (𝔪 : {I : Ideal A // I.IsMaximal}),
      haveI := 𝔪.2.isPrime;
      M.localizedAtPrime 𝔪.1 := by
  apply le_antisymm
  · exact le_iInf fun ⟨𝔪, h𝔪⟩ =>
      M.le_localizedAtPrime 𝔪
  · intro x hx
    simp only [Submodule.mem_iInf] at hx
    have htop : M.conductor x = ⊤ := by
      by_contra h
      obtain ⟨𝔪, h𝔪, hle⟩ :=
        Ideal.exists_le_maximal _ h
      exact
        M.conductor_not_le_of_mem_localizedAtPrime
          x 𝔪 (hx ⟨𝔪, h𝔪⟩) hle
    have h1 : (1 : A) • x ∈ M :=
      show (1 : A) ∈ M.conductor x by
        rw [htop]; trivial
    simpa using h1

omit [IsDomain A] in
/-- The intersection over maximal ideals equals
the intersection over prime ideals.
This follows from the two equalities above. -/
theorem
    Submodule.iInf_localizedAtPrime_maximal_eq_iInf_localizedAtPrime
    (M : Submodule A V) :
    (⨅ (𝔪 : {I : Ideal A // I.IsMaximal}),
      haveI := 𝔪.2.isPrime;
      M.localizedAtPrime 𝔪.1) =
    (⨅ (𝔭 : Ideal A) (_ : 𝔭.IsPrime),
      M.localizedAtPrime 𝔭) := by
  rw [← M.eq_iInf_localizedAtPrime_maximal,
    ← M.eq_iInf_localizedAtPrime]

end Proposition_2_6
```

An important special case of this proposition occurs when $`K = \operatorname{Frac} A` and $`V = K`, in which case $`M` is an $`A`-submodule of $`K`. Every ideal $`I` of $`A` is an $`A`-submodule of $`K`, and can thus be localized as above. The localization of $`I` (as an $`A`-module) at a prime ideal $`\mathfrak{p}` of $`A` is the same thing as the extension of $`I` (as an $`A`-ideal) to the localization of $`A` at $`\mathfrak{p}`. In other words,

$$`I_{\mathfrak{p}} = \{i/s : i \in I, s \in A - \mathfrak{p}\} = \{ia/s : i \in I, a \in A, s \in A - \mathfrak{p}\} = IA_{\mathfrak{p}}.`

We also have the following corollary of Proposition 2.6.

```lean
section Discussion_02_06a

variable {A : Type*} [CommRing A] [IsDomain A]
  {S : Type*} [CommRing S] [Algebra A S]
  (M : Submonoid A) [IsLocalization M S]

/-! ### Claim: I_𝔭 = IA_𝔭

The localization of an ideal I (viewed as an
A-module) with respect to
a multiplicative set S is the same as the
extension (image) of I under
the localization map A → S⁻¹A.

Mathlib captures this via
`Algebra.idealMap_isLocalizedModule`: the map
`Algebra.idealMap I : I →ₗ[A] (I.map
(algebraMap A S))` is a localized module,
meaning the target `I.map (algebraMap A S)`
satisfies the universal property
of S⁻¹I. -/

-- The ideal extension map
-- I → I.map(algebraMap A S) is a localized module
recall Algebra.idealMap_isLocalizedModule

/-- For a concrete `Localization`, the extension
of an ideal I is the localized
module of I — i.e., the canonical S⁻¹A-submodule
generated by I in S⁻¹A
equals I.map (algebraMap A
(Localization M)). -/
example (I : Ideal A) :
    IsLocalizedModule M
      (Algebra.idealMap
        (S := Localization M) I) :=
  inferInstance

end Discussion_02_06a
```

# Corollary 2.7
%%%
number := false
%%%

_Corollary 2.7._ _Let $`A` be an integral domain. Every ideal $`I` of $`A` (including $`I = A`) is equal to the intersection of its localizations at the maximal ideals of $`A`, and also to the intersection of its localizations at the prime ideals of $`A`._

```lean
section Corollary_2_7

variable {A : Type*} [CommRing A] [IsDomain A]

/-! ## Localization of an ideal at a prime

For an ideal I of A and a prime 𝔭, the
localization
I_𝔭 ∩ A = {a ∈ A | ∃ s ∉ 𝔭, s·a ∈ I}
is again an ideal of A. This is the contraction
of the extended ideal I·A_𝔭 back to A. -/

/-- The localization of an ideal I at a prime
ideal 𝔭, contracted back to A.
An element a ∈ A lies in I_𝔭 ∩ A iff there exists
s ∈ A \ 𝔭 with s * a ∈ I. -/
def Ideal.localizedAtPrime (I : Ideal A)
    (𝔭 : Ideal A) [𝔭.IsPrime] :
    Ideal A where
  carrier :=
    { a : A | ∃ s : 𝔭.primeCompl,
        (s : A) * a ∈ I }
  add_mem' := by
    rintro x y ⟨s, hsx⟩ ⟨t, hty⟩
    exact ⟨⟨s * t,
      𝔭.primeCompl.mul_mem s.2 t.2⟩, by
      have : (↑s * ↑t) * (x + y) =
          ↑t * (↑s * x) + ↑s * (↑t * y) := by
        ring
      rw [this]
      exact I.add_mem
        (I.mul_mem_left ↑t hsx)
        (I.mul_mem_left ↑s hty)⟩
  zero_mem' :=
    ⟨⟨1, 𝔭.primeCompl.one_mem⟩, by simp⟩
  smul_mem' := by
    intro c a ⟨⟨s, hs⟩, hsa⟩
    exact ⟨⟨s, hs⟩, by
      rw [smul_eq_mul, mul_left_comm]
      exact I.mul_mem_left c hsa⟩

omit [IsDomain A] in
/-- I is contained in each of its
localizations. -/
theorem Ideal.le_localizedAtPrime
    (I : Ideal A)
    (𝔭 : Ideal A) [𝔭.IsPrime] :
    I ≤ I.localizedAtPrime 𝔭 := by
  intro x hx
  exact ⟨⟨1, 𝔭.primeCompl.one_mem⟩,
    by simpa using hx⟩

omit [IsDomain A] in
/-- If 𝔭 ⊆ 𝔮, then I_𝔮 ⊆ I_𝔭 (localizing at a
smaller prime gives a larger ideal). -/
theorem Ideal.localizedAtPrime_anti
    (I : Ideal A)
    {𝔭 𝔮 : Ideal A} [𝔭.IsPrime] [𝔮.IsPrime]
    (h : 𝔭 ≤ 𝔮) :
    I.localizedAtPrime 𝔮 ≤
      I.localizedAtPrime 𝔭 := by
  intro a ⟨⟨s, hs⟩, hsa⟩
  exact ⟨⟨s, fun hs𝔭 => hs (h hs𝔭)⟩, hsa⟩

/-! ## The main corollary

**Proof strategy** (following the book): This is
a direct consequence of Proposition 2.6.
An ideal I of A can be viewed as an A-submodule
of K = Frac(A) via the algebra map.
Under this identification, the localization of I
at 𝔭 (as a submodule of K) corresponds
to I.localizedAtPrime 𝔭 pulled back to A.
Proposition 2.6 gives
I = ⋂_𝔭 I_𝔭 = ⋂_𝔪 I_𝔪 as submodules of K,
which translates to the ideal version.

Alternatively, the same conductor argument
applies directly: for a ∈ ⋂_𝔪 I_𝔪, the
conductor {s ∈ A | s·a ∈ I} is not contained in
any maximal ideal, hence equals A. -/

omit [IsDomain A] in
/-- **Corollary 2.7** (prime ideals version).
Every ideal I of A equals the intersection
of its localizations at all prime ideals:
  I = ⋂_𝔭 I.localizedAtPrime 𝔭
where 𝔭 ranges over prime ideals of A. -/
theorem Ideal.eq_iInf_localizedAtPrime
    (I : Ideal A) :
    I = ⨅ (𝔭 : Ideal A) (_ : 𝔭.IsPrime),
      I.localizedAtPrime 𝔭 := by
  ext a
  simp only [Ideal.mem_iInf]
  constructor
  · intro ha 𝔭 _
    exact I.le_localizedAtPrime 𝔭 ha
  · intro ha
    -- The conductor J = {s ∈ A | s * a ∈ I} is
    -- not contained in any prime ideal
    -- because for each prime 𝔭, ha gives s ∉ 𝔭
    -- with s * a ∈ I, so s ∈ J \ 𝔭.
    -- Hence J = A, so 1 ∈ J, meaning a ∈ I.
    by_contra ha_notin
    -- The conductor J = {s | s*a ∈ I}
    let J : Ideal A := {
      carrier := { s : A | s * a ∈ I }
      add_mem' := fun {x y} hx hy => by
        simp only [Set.mem_setOf_eq,
          add_mul] at *
        exact I.add_mem hx hy
      zero_mem' := by simp [I.zero_mem]
      smul_mem' := fun c x hx => by
        simp only [Set.mem_setOf_eq,
          smul_eq_mul, mul_assoc] at *
        exact I.mul_mem_left c hx }
    -- J ≠ ⊤ since 1 * a = a ∉ I
    have hJ_ne_top : J ≠ ⊤ := by
      intro h; apply ha_notin
      have : (1 : A) ∈ J :=
        h ▸ Submodule.mem_top
      simpa [J] using this
    obtain ⟨𝔪, h𝔪max, hJ𝔪⟩ :=
      J.exists_le_maximal hJ_ne_top
    have ha𝔪 := ha 𝔪 h𝔪max.isPrime
    obtain ⟨⟨s, hs⟩, hsa⟩ := ha𝔪
    exact hs (hJ𝔪 hsa)

omit [IsDomain A] in
/-- **Corollary 2.7** (maximal ideals version).
Every ideal I of A equals the intersection
of its localizations at all maximal ideals:
  I = ⋂_𝔪 I.localizedAtPrime 𝔪
where 𝔪 ranges over maximal ideals of A. -/
theorem Ideal.eq_iInf_localizedAtPrime_maximal
    (I : Ideal A) :
    I = ⨅ (𝔪 : {J : Ideal A // J.IsMaximal}),
      haveI := 𝔪.2.isPrime;
      I.localizedAtPrime 𝔪.1 := by
  ext a
  simp only [Ideal.mem_iInf, Subtype.forall]
  constructor
  · intro ha 𝔪 h𝔪
    haveI := h𝔪.isPrime
    exact I.le_localizedAtPrime 𝔪 ha
  · intro ha
    by_contra ha_notin
    let J : Ideal A := {
      carrier := { s : A | s * a ∈ I }
      add_mem' := fun {x y} hx hy => by
        simp only [Set.mem_setOf_eq,
          add_mul] at *
        exact I.add_mem hx hy
      zero_mem' := by simp [I.zero_mem]
      smul_mem' := fun c x hx => by
        simp only [Set.mem_setOf_eq,
          smul_eq_mul, mul_assoc] at *
        exact I.mul_mem_left c hx }
    have hJ_ne_top : J ≠ ⊤ := by
      intro h; apply ha_notin
      have : (1 : A) ∈ J :=
        h ▸ Submodule.mem_top
      simpa [J] using this
    obtain ⟨𝔪, h𝔪max, hJ𝔪⟩ :=
      J.exists_le_maximal hJ_ne_top
    haveI := h𝔪max.isPrime
    have ha𝔪 := ha 𝔪 h𝔪max
    obtain ⟨⟨s, hs⟩, hsa⟩ := ha𝔪
    exact hs (hJ𝔪 hsa)

omit [IsDomain A] in
/-- The intersection over maximal ideals equals
the intersection over prime ideals. -/
theorem
    Ideal.iInf_localizedAtPrime_maximal_eq_iInf_localizedAtPrime
    (I : Ideal A) :
    (⨅ (𝔪 : {J : Ideal A // J.IsMaximal}),
      haveI := 𝔪.2.isPrime;
      I.localizedAtPrime 𝔪.1) =
    (⨅ (𝔭 : Ideal A) (_ : 𝔭.IsPrime),
      I.localizedAtPrime 𝔭) := by
  rw [← I.eq_iInf_localizedAtPrime_maximal,
    ← I.eq_iInf_localizedAtPrime]

end Corollary_2_7
```

# Example 2.8
%%%
number := false
%%%

_Example 2.8._ If $`A = \mathbb{Z}` then $`\mathbb{Z} = \bigcap_p \mathbb{Z}_{(p)}` in $`\mathbb{Q}`.

```lean
section Example_2_8

/-! ## The Mathlib result for general integral
domains

The general result is that any integral domain
equals the intersection of its
localizations at all prime ideals (or all maximal
ideals), viewed inside its
fraction field. -/

-- General version for prime ideals
#check @PrimeSpectrum.iInf_localization_eq_bot
-- General version for maximal ideals
#check @MaximalSpectrum.iInf_localization_eq_bot

/-! ## Specialization to ℤ and ℚ

ℤ = ⋂_p ℤ_(p) inside ℚ. Each ℤ_(p) is the
localization of ℤ at the complement
of the prime ideal (p), and the intersection of
all these localizations (as
subalgebras of ℚ) is exactly the image of ℤ
in ℚ. -/

/-- **Example 2.8.** ℤ equals the intersection of
all its localizations ℤ_(p) inside ℚ,
where p ranges over the prime ideals of ℤ. This
is the specialization of the general
result `PrimeSpectrum.iInf_localization_eq_bot`
to ℤ and ℚ. -/
theorem Int.eq_iInf_localization_atPrime :
    ⨅ v : PrimeSpectrum ℤ,
      Localization.subalgebra.ofField ℚ _
        v.asIdeal.primeCompl_le_nonZeroDivisors
    = ⊥ :=
  PrimeSpectrum.iInf_localization_eq_bot ℤ ℚ

/-- Maximal ideals version: ℤ = ⋂_p ℤ_(p) where
p ranges over maximal ideals only. -/
theorem Int.eq_iInf_localization_atMaximal :
    ⨅ v : MaximalSpectrum ℤ,
      Localization.subalgebra.ofField ℚ _
        v.asIdeal.primeCompl_le_nonZeroDivisors
    = ⊥ :=
  MaximalSpectrum.iInf_localization_eq_bot ℤ ℚ

end Example_2_8
```

Proposition 2.6 and Corollary 2.7 are powerful tools, because they allow us to work in local rings (rings with just one maximal ideal), which often simplifies matters considerably. For example, to prove that an ideal $`I` in an integral domain $`A` satisfies a certain property, it is enough to show that this property holds for all its localizations $`I_{\mathfrak{p}}` at prime ideals $`\mathfrak{p}` and is preserved under intersections. We now want to consider rings $`A` that satisfy some further assumptions that make its localizations even easier to work with.
